services:
  consumer:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cms-transcode-consumer
    working_dir: /
    command: python src/consumer/request_consumer.py
    volumes:
      - ./src:/src
    environment:
      - PYTHONPATH=/
    depends_on:
      - rabbitmq
      - redis

  worker:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cms-transcode-worker
    working_dir: /
    command: celery -A src.worker.celery_worker.celery_app worker --loglevel=info --concurrency=1
    volumes:
      - ./src:/src
    environment:
      - PYTHONPATH=/src
    depends_on:
      - rabbitmq
      - redis

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672      # AMQP 포트
      - 15672:15672    # 웹 UI 포트
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:7
    container_name: redis
    ports:
      - 6379:6379
