services:
  consumer:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cms-transcode-consumer
    working_dir: /
    command: python src/consumer/request_consumer.py
    volumes:
      - ./src:/src
    environment:
      - PYTHONPATH=/
    depends_on:
      - redis

  worker:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cms-transcode-worker
    working_dir: /
    command: celery -A src.worker.celery_worker.celery_app worker --loglevel=info --concurrency=1 -Q celery.transcode
    volumes:
      - ./src:/src
    environment:
      - PYTHONPATH=/src
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis
    ports:
      - 6379:6379
