apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-transcode-worker
  namespace: cms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cms-transcode-worker
  template:
    metadata:
      labels:
        app: cms-transcode-worker
    spec:
      containers:
      - name: cms-transcode-worker
        image: ghcr.io/callein/cms-transcode-worker:v1.0.0
        command: [ "celery", "-A", "src.worker.celery_worker.celery_app", "worker", "--loglevel=info", "--concurrency=1", "-Q", "celery.transcode" ]
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: true
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"      # 1 core
          limits:
            memory: "2Gi"
            cpu: "2000m"      # 2 core
        livenessProbe:
          exec:
            command: ["celery", "-A", "src.worker.celery_worker.celery_app", "inspect", "ping"]
          initialDelaySeconds: 60
          periodSeconds: 30
        envFrom:
        - secretRef:
            name: cms-transcode-env
        env:
        - name: PYTHONPATH
          value: "/src"